version: "3.9"
   
services:
  web:
    build: .
    env_file: # if .env in root, we have to show .env here must
      - ./.env
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
